FROM node:8.16.0

RUN apt-get update \
  && apt-get install git \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    -y \
  && git config --global user.email 'integration@dx26.io' \
  && git config --global user.name 'DX26 CI Bot' \
  && curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
  && echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
  && apt-get update \
  && apt-get install git docker-ce-cli -y
